Consolidate openTable API in CorfuStore.
CorfuDB/CorfuDB pull request #2732
Opened 2020-08-20 01:13 UTC by pankti-m

openTable() currently has two versions, depending on whether a table has been seen by the runtime.  This change consolidates the apis.

2020-08-20 01:27 UTC, WenbinZhu commented
I think instead of removing the second openTable() API, we can rename it to getTable(), because it actually an existing fetch table.

2020-09-10 17:57 UTC, hisundar commented on runtime/src/main/java/org/corfudb/runtime/collections/TxBuilder.java
> +    TxBuilder update(@Nonnull final String tableName,
What is done here is interesting, it looks like the caller can actually specify a delta update and it is up to the database to apply the update.
Right now you have implemented it as a classic read-modify-write cycle. But in the future we could have corfu defer the application of the 'arg' or delta here and lazily apply them (say at compaction). This is a powerful feature provided by other databases and if the goal is to accomplish this functionality perhaps we can just rename this function to call it 
merge(), the Bifunction as the mergeOperator and the arg as the delta?
Later we can think of optimizing this in corfu to support lazy merge to defer the read in the read-modify-write cycle.

2020-09-10 17:57 UTC, hisundar commented on runtime/src/main/java/org/corfudb/runtime/collections/TxBuilder.java
> +            throw new IllegalArgumentException(
This has implications on transaction abort - right now you want the transaction to abort on this illegalArgumentException, so perhaps you want to throw a runtime exception instead that wraps an abortCause?

2020-09-12 00:16 UTC, hisundar requested changes
please feel free to abandon this change as it has been absorbed into this PR
https://github.com/CorfuDB/CorfuDB/pull/2766

2021-02-01 05:53 UTC, pankti-m commented
Closing as the change has been absorbed in PR #2766

2021-02-01 05:53 UTC, closed without merging