More granular reads and writes
CorfuDB/CorfuDB pull request #2983
Opened 2021-06-14 20:17 UTC by PavelZaytsev

## Overview

Description:

Distinguish address space reads and writes by a stream

2021-06-14 20:27 UTC, xnull approved these changes

2021-06-14 22:06 UTC, hisundar requested changes
Do you want to remove the readTxn writeTxn readWriteTxn metrics from UFO as part of this change since they achieve the same thing or keep those and make these generic?

2021-07-07 23:16 UTC, hisundar approved these changes

2021-07-13 15:34 UTC, xnull approved these changes
looks good

2022-09-02 00:02 UTC, closed without merging