Fix runOrchestrator when managerStatus is null
CorfuDB/CorfuDB pull request #3478
Opened 2023-01-12 07:06 UTC by SravanthiAshokKumar

Return on cases when managerStatus is unable to be acquires as the runOrchestrator method runs every 10s

## Overview

Description:

Why should this be merged: 

Related issue(s) (if applicable): #<number>

## Checklist (Definition of Done):

- [ ] There are no TODOs left in the code
- [ ] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [ ] Change is covered by automated tests
- [ ] Public API has Javadoc

2023-01-14 02:52 UTC, hisundar requested changes
I dont see the actual code change - I only see the log warn to error, am I missing something?

2023-01-17 01:30 UTC, SravanthiAshokKumar commented
@hisundar I can see the code changes. Not sure why you aren't able to see.

2023-01-17 01:37 UTC, hisundar approved these changes

2023-01-17 04:03 UTC, zfrenette approved these changes

2023-01-17 06:17 UTC, merged